#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=40gb,walltime=20:00:00
#PBS -N bl.freesurfer
#SBATCH --job-name=test-hello
#SBATCH --ntasks-per-node=8
#SBATCH --mem=40G
#SBATCH --time=20:00:00
set -e
set -x

# Load proxy module (if your cluster provides one)
module load proxy


singularity exec --disable-cache  docker://brainlife/mne-freesurfer:7.3.2-1.2.1
