#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=40gb,walltime=20:00:00
#PBS -N bl.freesurfer

#SBATCH --ntasks-per-node=8
#SBATCH --mem=40G
#SBATCH --time=20:00:00

set -e
set -x

if [ -n "$FREESURFER_LICENSE" ]; then
    echo $FREESURFER_LICENSE > license.txt
elif [ -n "$FS_LICENSE" ] && [ -f "$FS_LICENSE" ]; then
    cp "$FS_LICENSE" license.txt
else
    echo "Please set FREESURFER_LICENSE or FS_LICENSE in resource environment" && exit 1
fi

singularity exec \
  -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
  docker://aunnikri642/app-freesurfer-mne-source-recon \
  bash ./freesurfer.sh
